// export {default as SK81} from '/sk8-1.webp'
// export {default as SK82} from './/sk8-2.png'
// export {default as SK83} from './/sk8-3.png'
// export {default as SK84} from './/sk8-4.png'
// export {default as SK85} from '/sk8-5.png'
// export {default as SK86} from '/sk8-6.png'
// export {default as SK87} from '/sk8-7.png'
export {default as SK88} from './/sk8-5.jpg'
export {default as SK8t} from './/sket1.gif'
