import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import '@radix-ui/themes/styles.css';



const poppins = Poppins({
  weight: ["400", "900"], // Specify the font weights you want to include
  display: "swap", // Specify the font-display property
  subsets: ["latin"], // Include the "latin" subset
  variable: "--poppins-font", // Define a CSS variable for the font
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          {children}
      </body>
    </html>
  );
}
